name: Deploy Site

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - uses: utooland/setup-utoo@v1

      - run: npm i

      - run: npm run build -- --skip-clean

      - name: Deploy to Gitee
        timeout-minutes: 10
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gitee.com >> ~/.ssh/known_hosts

          git clone git@gitee.com:ant-design/5x.ant.design.git gitee-repo
          cd gitee-repo
          git checkout -B gh-pages
          rm -rf ./*
          cp -r ../temp-antd-build/_site/* .

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          echo "Adding files to git..."
          timeout 300 git add . || git add .
          echo "Create a commit and push to Gitee..."
          git commit -n -m "Deploy $(date '+%Y-%m-%d')" || true
          git push origin gh-pages --force
